#!/bin/bash -e

KNOCKOUTS_PERIOD=4

mkdir -p tmp

printer="srcomp print-schedule . --period $KNOCKOUTS_PERIOD"

$printer --output tmp/knockout-all-colours.pdf
$printer --plain --output tmp/knockout-plain.pdf

pdfjam --outfile knockouts.pdf \
	tmp/knockout-all-colours.pdf \
	tmp/knockout-plain.pdf

evince knockouts.pdf

echo '-------'
echo -n "Print document? [Y/n]: "
read do_print
if [ -z "$do_print" ] || [ "$do_print" == "Y" ] || [ "$do_print" == "y" ]
then
	echo "Printing knockouts.pdf"
	if [ "$1" != "--dry-run" ]
	then
		lp knockouts.pdf
	fi
fi
